### ISSUE TITLE
Feature request: 增加cdn选项或者采用webpack打包

### ISSUE THREAD

**Issue by yml2213** [Raka-loah/SRK-Toolbox#12]
不管采用docker部署  还是https://btsrk.me/  访问  
由于main.js  文件过大  (10M)多
造成网络请求时间超过十秒,  但是本地的不能多端同步
希望大佬看下怎么优化下呀

![WechatIMG114](https://github.com/Raka-loah/SRK-Toolbox/assets/75053913/6cb5f5e4-86d1-4b7b-93d4-c707c268dbc7)

**Comment by Raka-loah** [comment]
btsrk.me太慢是我的错因为买不起更贵的VPS了😭，这个香港小水管是10M的所以还不错你都跑满了（不是），CDN的话之前放在Cloudflare但是开了更慢（毕竟是Cloudflare）所以关了……
至于Webpack，CyberChef这货本身就是Webpack打包出来的，而且优化它超出我的能力范围了（我只是个业余写Python的）……

下一步在考虑上Netlify或者Firebase Hosting，不过之前试过的情况国内访问速度都不咋样
