### ISSUE TITLE
麻烦来一份dockerhub的镜像

### ISSUE THREAD

**Issue by yw9381** [Raka-loah/SRK-Toolbox#6]
想要在k8s里部署，但是dockerhub上并没有现成的镜像，本地编译又不方便及时跟踪上游，麻烦利用github action作自动构建并push到dockerhub

**Comment by Raka-loah** [comment]
已推送到docker hub：`docker pull rakaloah/srk-toolbox`

**Comment by yw9381** [comment]
搞个CI，跟随官方版本号一起走？也方便后续更新

**Comment by Raka-loah** [comment]
用的就是CyberChef原版那个on push tag v*的action，我只是十分担心会被我改崩然后还推过去了🤣

**Comment by yw9381** [comment]
我刚看了下在dockerhub上的镜像tag里只有latest

**Comment by Raka-loah** [comment]
已修改，从v9.54.0之后按官方版本号打tag
